### ISSUE TITLE
Need an option to have only atomic values editable

### ISSUE THREAD

**Issue by nileshtrivedi** [DavidDurman/FlexiJsonEditor#26]
Currently, a text field is generated for the object (or array) itself too where the complete json can be viewed and edited. To make editing more user-friendly, there should be an option so that a property's value can be edited only by going down deep in the hierarchy and finding the text field for that property. In other words, there would be no text fields for arrays or objects, only for numbers and strings.

**Comment by DavidDurman** [comment]
Good suggestion. A flag for turning this off would make it more "programmer's friendly" but it can be done already by applying the following CSS rule:

``` css
.item.array > .value,
.item.object > .value {
    display: none;
}
```

**Comment by nileshtrivedi** [comment]
Thanks, @DavidDurman . This is a good enough solution for now.
